export const bookPublishers = {
  cs: [
    '',
    '65. pole',
    'Academia',
    'Albatros (ČR)',
    'Argo',
    'Baronet',
    'BB art',
    'Computer Press',
    'CooBoo',
    'Crew',
    'Československý spisovatel',
    'Dybbuk',
    'Egmont (ČR)',
    'Epocha (ČR)',
    'Fantom Print',
    'Fragment (ČR)',
    'Grada',
    'Harlequin',
    'Host',
    'Ikar (ČR)',
    'Ivo Železný',
    'Jota',
    'Kniha Zlín',
    'Knižní klub',
    'Laser books (Laser)',
    'Levné knihy',
    'Mladá fronta',
    'MOBA',
    'Naše vojsko',
    'Odeon',
    'Orbis',
    'Paseka',
    'Pragma',
    'Práh',
    'Slovart (ČR)',
    'SNDK - Státní nakladatelství dětské literatury',
    'Svojtka & Co',
    'Talpress',
    'Triton',
    'XYZ (ČR)',
  ],
};
