export const bookGenres = {
  cs: [
    '',
    'Architektura',
    'Biografie a memoáry',
    'Cestopisy a místopisy',
    'Citáty a přísloví',
    'Detektivky',
    'Divadelní hry',
    'Dívčí romány',
    'Dobrodružné',
    'Doprava',
    'Duchovní literatura',
    'Dům a byt',
    'Ekologie, životní prostředí',
    'Ekonomie a obchod',
    'Encyklopedie',
    'Erotika',
    'Esoterika, astrologie, okultismus',
    'Fantasy',
    'Fejetony, eseje',
    'Filozofie',
    'Fotopublikace',
    'Historické romány',
    'Historie',
    'Hobby',
    'Horory',
    'Hudebniny',
    'Humor',
    'Komiksy',
    'Kuchařky',
    'Leporelo',
    'Literatura česká',
    'Literatura faktu',
    'Literatura naučná',
    'Literatura světová',
    'Mapy a atlasy',
    'Matematika a logika',
    'Mytologie',
    'Náboženství',
    'Novely',
    'Obrázkové knihy',
    'Omalovánky',
    'Osobní rozvoj a styl',
    'PC literatura',
    'Poezie',
    'Pohádky',
    'Politologie, mezinárodní vztahy',
    'Pověsti',
    'Povídky',
    'Právo',
    'Pro děti a mládež',
    'Pro nejmenší',
    'Příroda, zvířata',
    'Přírodní vědy',
    'Psychologie a pedagogika',
    'Rodina',
    'Romány',
    'Sci-fi',
    'Sociologie',
    'Sport',
    'Šikovné děti - tvoření, hry, styl',
    'Technika a elektro',
    'Thrillery',
    'Učebnice a slovníky',
    'Umění',
    'Válečné',
    'Věda',
    'Vesmír',
    'Young Adult',
    'Zdraví',
    'Zemědělství',
    'Žurnalistika, publicistika',
  ],
};
